### ISSUE TITLE
Issue #2 -- Hacktoberfest-2021

### ISSUE THREAD

**Issue by JennEYoon** [WomensCodingCircle/ai-deep-learning-python#2]
Add any new public resource or write a short post about AI, deep learning, or machine learning.  Anything that is not a substantial repeat of existing resource will be accepted.  Please use markdown formatting and save any new post as a ***somepost.md*** file.  You may also modify an existing ***.md*** file with your new resource or post.  

These two files can be edited as part of #hacktoberfest-2021.  Add your resource(s) directly in the file on your forked repo.  
  * books-top5-ml-dl.md  
  * python-ml-resources.md  

Help on markdown formatting:  https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf  
Note Github uses a slightly different version of Markdown.

**Comment by noviicee** [comment]
@JennEYoon I wish to add a short article on AI, and attach some resources as well.

**Comment by HiruniPerera** [comment]
@JennEYoon I too wish to add an article on AI.Can you please kindly assign me too?

**Comment by alisha-a** [comment]
/assign document for post on machine learning.
I wish to write an article on ML.

**Comment by JennEYoon** [comment]
Hi alisha-a,  
You can go right ahead.  No need to first ask to be assigned.  Create a fork on your Github account.  Add an item to an existing file on books or other resources, or upload a new text file in .md markdown format.  Then create a pull request.  I will see it and merge it with this repo.  

:-)  Jennifer Yoon

**Comment by JennEYoon** [comment]
Thank you @HiruniPerera and @noviicee for creating a PR during #Hactoberfest-2021.  
Ooohoo, way to go!  Your posts have been merged and accepted.  

Jennifer Yoon

**Comment by JennEYoon** [comment]
Dear All,  
I've added topic "hacktoberfest" to this repo, so now it should show up on DigitalOcean progress page as a participating repo.  I've tested it out, and it seems to work.  Thank you!  Jennifer Yoon

**Comment by noviicee** [comment]
Thank you @JennEYoon

**Comment by JennEYoon** [comment]
@noviicee 
Hi noviicee Anamika, you're welcome!  
I hope this will get you started on a new habit of daily github commits.  Hactoberfest and Women Who Code (NoVa) Meetup members helped me get started with Github back in 2018-19.  

If you are looking for more easy repos for hacktoberfest, my personal repo is sponsoring one.  
https://github.com/JennEYoon/deep-learning/issues/17  
 
:-D  Jennifer Yoon

**Comment by JennEYoon** [comment]
@alisha-a   Hi Alisha A,  
You have not created a PR for hacktoberfest yet.  

I've made it even easier.  Add one book or online resource link and name.  See the 2 files you may edit on the updated issue description.  Edit one of the files by adding your new item, on your fork's copy.  Then from your github fork, create a pull request.  I will see it and merge it.  I've added "hacktoberfest" to this repo's subject, so it will be counted.  I've tested it now and it works.  

Hope this will help you get started on a journey of daily Github commits!  =.D  Happy Coding.  
Jennifer Yoon

**Comment by JennEYoon** [comment]
Hacktoberfest 2021 is over and I am closing out this issue.  
You can continue to contribute resources and links related to deep learning on this repo.  
See Issue #1.
